Pagination ticket - add 5 pages to the project with homepage css laya…
ripsamuel/godBootcamp pull request #2
Opened 2023-03-01 15:47 UTC by ripsamuel

…out and Next button
![Screen Shot 2023-03-01 at 10 46 55 AM](https://user-images.githubusercontent.com/104223467/222190305-b32b2c82-db38-4b75-9ea1-933caaede9a9.png)

2023-03-01 17:09 UTC, Theweeksad requested changes
please, use the file scheme to organize the css, as in the screenshot I sent you of the files, to have everything more organized.

2023-03-02 00:26 UTC, johanmendezb requested changes
as a good practice all left and right margins are applied to the main/highest level container so you don't have to add it manually on each section or element on the page, for example if tomorrow, this value es not 2 but 5, you may have to look for several places to update it, instead you can just add it in one place and the change will be global, making it easier to maintain.

check `CSS/layaout.css` lines *32, 48, 69, 70*

2023-03-02 00:26 UTC, johanmendezb commented on CSS/layaout.css
> +    line-height: 39.6px;
Please move these styles to the global styles file as they should be added globally and then inherit throughout of the project.
```suggestion    
```

2023-03-02 00:26 UTC, johanmendezb commented on CSS/layaout.css
>      top: 12rem;
avoid adding space to the top, instead try to use margins to push the content to the bottom, ie: marging-bottom

2023-03-02 00:26 UTC, johanmendezb commented on CSS/layaout.css
> +    line-height: 26.4px;
Same as above, these are global styles
```suggestion
```

2023-03-02 00:26 UTC, johanmendezb commented on CSS/layaout.css
>      line-height: 110%;
Move them to global styles.
```suggestion
```

2023-03-02 00:26 UTC, johanmendezb commented on CSS/layaout.css
> +    line-height: 17.6px;
Move them to global styles.

2023-03-02 03:26 UTC, closed without merging